# controllers:
#     resource: ../src/Controller/
#     type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController::home

panier:
    path: /
    controller: App\Controller\HomeController::panier

produit:
    path: /
    controller: App\Controller\HomeController::produit